[build]
builder = "NIXPACKS"

[deploy]
startCommand = "monet worker --server-url $MONET_SERVER_URL --pool ${MONET_WORKER_POOL:-default} --concurrency ${MONET_WORKER_CONCURRENCY:-10} --path agents"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
