"""Configuration subpackage.

Centralises every environment-variable read in the SDK and provides
typed, validated config objects for each deployable unit (server,
worker, client, CLI). See :mod:`monet.config._env` for the registry of
env var names and accessors, and :mod:`monet.config._schema` for the
schemas.

Every other module in monet should import env-var *names* from
:mod:`monet.config` (or read through a schema's ``load()``) rather than
calling ``os.environ.get`` directly. The one exception is
:mod:`monet.config._env` itself, which is the single boundary where the
SDK touches ``os.environ``.
"""

from __future__ import annotations

from ._env import (
    EXA_API_KEY,
    GEMINI_API_KEY,
    GROQ_API_KEY,
    HONEYCOMB_API_KEY,
    HONEYCOMB_DATASET,
    LANGFUSE_HOST,
    LANGFUSE_PUBLIC_KEY,
    LANGFUSE_SECRET_KEY,
    LANGSMITH_API_KEY,
    LANGSMITH_PROJECT,
    MONET_AGENT_TIMEOUT,
    MONET_API_KEY,
    MONET_ARTIFACTS_DIR,
    MONET_CHAT_GRAPH,
    MONET_CHAT_RESPOND_MODEL,
    MONET_CHAT_TRIAGE_MODEL,
    MONET_CONFIG_PATH,
    MONET_DISTRIBUTED,
    MONET_ENV_VARS,
    MONET_QUEUE_BACKEND,
    MONET_SERVER_URL,
    MONET_TRACE_FILE,
    MONET_WORKER_AGENTS,
    MONET_WORKER_CONCURRENCY,
    MONET_WORKER_HEARTBEAT_INTERVAL,
    MONET_WORKER_POLL_INTERVAL,
    MONET_WORKER_POOL,
    MONET_WORKER_SHUTDOWN_TIMEOUT,
    OTEL_EXPORTER_OTLP_ENDPOINT,
    OTEL_EXPORTER_OTLP_HEADERS,
    OTEL_SERVICE_NAME,
    REDIS_URI,
    TAVILY_API_KEY,
    ConfigError,
    agent_model_env,
    dispatch_secret_env,
    graph_role_env,
    pool_auth_env,
    pool_url_env,
    read_bool,
    read_enum,
    read_float,
    read_int,
    read_path,
    read_str,
)
from ._graphs import (
    DEFAULT_ENTRYPOINTS,
    DEFAULT_GRAPH_ROLES,
    Entrypoint,
    load_entrypoints,
    load_graph_roles,
)
from ._load import default_config_path, read_toml, read_toml_section
from ._schema import (
    ArtifactsConfig,
    AuthConfig,
    ChatConfig,
    CLIDevConfig,
    ClientConfig,
    ObservabilityConfig,
    OrchestrationConfig,
    QueueBackend,
    QueueConfig,
    ServerConfig,
    WorkerConfig,
)

__all__ = [
    "DEFAULT_ENTRYPOINTS",
    "DEFAULT_GRAPH_ROLES",
    "EXA_API_KEY",
    "GEMINI_API_KEY",
    "GROQ_API_KEY",
    "HONEYCOMB_API_KEY",
    "HONEYCOMB_DATASET",
    "LANGFUSE_HOST",
    "LANGFUSE_PUBLIC_KEY",
    "LANGFUSE_SECRET_KEY",
    "LANGSMITH_API_KEY",
    "LANGSMITH_PROJECT",
    "MONET_AGENT_TIMEOUT",
    "MONET_API_KEY",
    "MONET_ARTIFACTS_DIR",
    "MONET_CHAT_GRAPH",
    "MONET_CHAT_RESPOND_MODEL",
    "MONET_CHAT_TRIAGE_MODEL",
    "MONET_CONFIG_PATH",
    "MONET_DISTRIBUTED",
    "MONET_ENV_VARS",
    "MONET_QUEUE_BACKEND",
    "MONET_SERVER_URL",
    "MONET_TRACE_FILE",
    "MONET_WORKER_AGENTS",
    "MONET_WORKER_CONCURRENCY",
    "MONET_WORKER_HEARTBEAT_INTERVAL",
    "MONET_WORKER_POLL_INTERVAL",
    "MONET_WORKER_POOL",
    "MONET_WORKER_SHUTDOWN_TIMEOUT",
    "OTEL_EXPORTER_OTLP_ENDPOINT",
    "OTEL_EXPORTER_OTLP_HEADERS",
    "OTEL_SERVICE_NAME",
    "REDIS_URI",
    "TAVILY_API_KEY",
    "ArtifactsConfig",
    "AuthConfig",
    "CLIDevConfig",
    "ChatConfig",
    "ClientConfig",
    "ConfigError",
    "Entrypoint",
    "ObservabilityConfig",
    "OrchestrationConfig",
    "QueueBackend",
    "QueueConfig",
    "ServerConfig",
    "WorkerConfig",
    "agent_model_env",
    "default_config_path",
    "dispatch_secret_env",
    "graph_role_env",
    "load_entrypoints",
    "load_graph_roles",
    "pool_auth_env",
    "pool_url_env",
    "read_bool",
    "read_enum",
    "read_float",
    "read_int",
    "read_path",
    "read_str",
    "read_toml",
    "read_toml_section",
]
